# Generated by Django 4.0 on 2021-12-17 10:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price_per_kilo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('wasted_kilos', models.IntegerField(default=0)),
                ('estimated_price', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('entered_kilos', models.IntegerField(default=0)),
                ('estimated_price', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.employee')),
            ],
        ),
    ]
