# Generated by Django 4.0 on 2021-12-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_alter_entries_product_id_alter_entries_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
